name: Qualys WAS Scanner For GitHub Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Grant execute permissions to mvnw
        run: chmod +x ./mvnw
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build Spring Boot App
        run: ./mvnw clean package
      
      - name: Store Maven dependencies in cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      
      - name: Archive JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GitHubActions-Artifact
          path: target/GitHubActions-0.0.1-SNAPSHOT.jar
  
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: GitHubActions-Artifact
          path: ./
          
      - name: Run Spring Boot App
        run: java -jar ./GitHubActions-0.0.1-SNAPSHOT.jar
        env:
          PLATFORM: ${{ vars.PLATFORM }}
          API_SERVER: ${{ secrets.API_SERVER }}
          QUALYS_USERNAME: ${{ secrets.QUALYS_USERNAME }}
          QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
          USE_PROXY: ${{ vars.USE_PROXY }}
          PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
          PROXY_PORT: ${{ vars.PROXY_PORT }}
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          WEBAPP_ID: ${{ vars.WEBAPP_ID }}
          SCAN_NAME: ${{ vars.SCAN_NAME }}
          SCAN_TYPE: ${{ vars.SCAN_TYPE }}
          AUTH_RECORD: ${{ vars.AUTH_RECORD }}
          AUTH_RECORD_ID: ${{ vars.AUTH_RECORD_ID }}
          OPTION_PROFILE: ${{ vars.OPTION_PROFILE }}
          OPTION_PROFILE_ID: ${{ vars.OPTION_PROFILE_ID }}
          CANCEL_OPTION: ${{ vars.CANCEL_OPTION }}
          CANCEL_HOURS: ${{ vars.CANCEL_HOURS }}
          SEVERITY_CHECK: ${{ vars.SEVERITY_CHECK }}
          SEVERITY_LEVEL: ${{ vars.SEVERITY_LEVEL }}
          IS_FAIL_ON_QID_FOUND: ${{ vars.IS_FAIL_ON_QID_FOUND }}
          QID_LIST: ${{ vars.QID_LIST }}
          EXCLUDE: ${{ vars.EXCLUDE }}
          FAIL_ON_SCAN_ERROR: ${{ vars.FAIL_ON_SCAN_ERROR }}
          WAIT_FOR_RESULT: ${{ vars.WAIT_FOR_RESULT }}
          
      - name: Upload Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: Scan-Report
          path: ./outputs